version: '3.4'

services:
  dev:
    build: .
    container_name: srv_technipo_dev
    command: npm run dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: technipo_db
    environment:
      SA_PASSWORD: Dbatn@2023
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - database:/var/opt/mssql/data

volumes:
   database:
